plat: imx8m: Fix compile errors with active VAR_ENABLE_IMX_UART
Exemplary compile error for imx8mp:

plat/imx/imx8m/imx8mp/imx8mp_bl31_setup.c: In function 'bl31_early_platform_setup2':
plat/imx/imx8m/imx8mp/imx8mp_bl31_setup.c:242:40: error: 'console' undeclared (first use in this function)
  242 |                 IMX_CONSOLE_BAUDRATE, &console);
      |                                        ^~~~~~~

Fixes: 1997e363065a "plat: imx8m: Disable ATF console_imx_uart_register"
Signed-off-by: Markus Heidelberg <m.heidelberg@cab.de>
(cherry picked from commit bed39c167c883b335d5fc1046ce16e10a611b4c4)